### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dashezup** [ImJanindu/AnyDL-Bot#1]
## License issue

The source code of this [AnyDL-Bot project](https://github.com/ImJanindu/AnyDL-Bot/commit/68466fa022a243db6110329f96d67e80ca98ba21) is based on my tgbot project, ytdl_with_button plugin which [first appear at 2021-01-15](https://github.com/dashezup/tgbot/commit/51a83a696a7920e66a4f09a762c867d3dc86b93e), the whole tgbot project including the ytdl_with_button plugin is licensed under [AGPL-3.0-or-later](https://github.com/dashezup/tgbot/blob/dev/LICENSE). idk where did you get the source code, but I'm sure it's based on my work.

A TL; DR for AGPLv3 license would be that a modified work of an AGPLv3 licensed projects should be licensed under the same License no matter if it's a public release or provide as software as service.

But currently your AnyDL-Bot project does not include the license text nor mention license in any other ways, please add the AGPL license to the repo.

btw it's nice that you open sourced the project.

**Comment by dashezup** [comment]
And other issues which is because it's based on my old codes, you may want to fix them

1. OpenCC `s2tw` is the library for converting Simplified Chinese characters to Traditional Chinese characters, you may not need it. but it's your choice to include it or not.
2. Telegram iOS and Telegram macOS have the problem to play webm files. (plays the first a few seconds and then skips to the next), I recently [solved this](https://github.com/callsmusic/tgmusicbot/blob/f1632ace1a852ffceefd54579a1f61ac808b022b/tgmusicbot.py#L153-L157) by using ffmpeg to copy the audio stream (no audio quality loss) and remux in opus. But this will require `ffmpeg` as an additional dependence, you can use a buildpack for Heroku in this case (you may want to check how I did it with [callsmusic/tgmusicbot](https://github.com/callsmusic/tgmusicbot))
https://github.com/ImJanindu/AnyDL-Bot/blob/59be41666de0029d7b8ed4ee77057cf1a5abb67f/jebot.py#L159-L163

**Comment by ImJanindu** [comment]
> ## License issue
> The source code of this [AnyDL-Bot project](https://github.com/ImJanindu/AnyDL-Bot/commit/68466fa022a243db6110329f96d67e80ca98ba21) is based on my tgbot project, ytdl_with_button plugin which [first appear at 2021-01-15](https://github.com/dashezup/tgbot/commit/51a83a696a7920e66a4f09a762c867d3dc86b93e), the whole tgbot project including the ytdl_with_button plugin is licensed under [AGPL-3.0-or-later](https://github.com/dashezup/tgbot/blob/dev/LICENSE). idk where did you get the source code, but I'm sure it's based on my work.
> 
> A TL; DR for AGPLv3 license would be that a modified work of an AGPLv3 licensed projects should be licensed under the same License no matter if it's a public release or provide as software as service.
> 
> But currently your AnyDL-Bot project does not include the license text nor mention license in any other ways, please add the AGPL license to the repo.
> 
> btw it's nice that you open sourced the project.

Ok ✌
